### ISSUE TITLE
choice type in the email submitted shows 0 value in the first array

### ISSUE THREAD

**Issue by biggsxox** [jadwigo/SimpleForms#17]
Here is the field options in my form i have on my config file

```
charges:
      type: choice
      expanded: true
      required: true
      multiple: true
      label: Check all the services you would like to include in your support package:
      choices: [Monthly, Per-hour, Pay As You Go, One Time Consultation]
      required: true
```

then i tested by submitting the form with monthly and one time consultation selected and i got the email and the email listed the first option as 0  as below

charges: 0, One Time Consultation

any idea what happened?

**Comment by jadwigo** [comment]
Sorry for the late reply

The zero value is weird, it should be there only if there is an empty option in your form. Did you have the form field as optional (required:false) earlier?

You could try to be more explicit about the choices like in the following example, I hope that helps

```
charges:
      type: choice
      expanded: true
      required: true
      multiple: true
      label: Check all the services you would like to include in your support package:
      choices:
         monthly: Monthly
         hourly: Per-hour
         payasyougo: "Pay As You Go"
         onetime: "One Time Consultation"
```

BTW. You only need to set `required:true` once.
