### ISSUE TITLE
use_as / use_with does not work

### ISSUE THREAD

**Issue by melcarthus** [jadwigo/SimpleForms#30]
As far as I know there is no way to send an confirmation e-mail. But there is a way to send a copy of the form to the sender of the address with use_ass and use_with. But this does not work. I get no message in my inbox that I used as the sending party of the form. I only receive an e-mail in my inbox that is set as te recipient.

``` yaml
contact:
    mail_subject: "site | Mail"
      recipient:
        type: email
        use_as: to_email|from_email|cc_email|bcc_email
        use_with: email
      recipient_email: mail@mail.nl
     recipient_name: Name
      testing:
        type: text
        label: testing
      fields:
        name:
          type: text
          required: true
          label: Naam
          placeholder: Je naam ..
         email:
          type: email
          label: E-mailadres
          required: true
          placeholder: Je e-mailadres ..
        message:
          type: textarea
          label: Bericht
          required: true
          placeholder: Je bericht ..
      button_text: Versturen
```
