### ISSUE TITLE
Add option to configure constraints

### ISSUE THREAD

**Issue by j92** [jadwigo/SimpleForms#34]
Hi,

I would like to add an option to SimpleForms to configure the constraints for every field, so that you can easily customize the default validation messages.

My idea is to do something similar to this:

```
fieldconstraints:
        notblank:
          message: Please fill in your email address
        length:
          min: 2
          max: 100
          minMessage: Your email address has to be at least {{ limit }} characters long
          maxMessage: Your email address cannot be longer then {{ limit }} characters
        email:
          message: Please give us a valid email address 
```

If you think this is a useful function, then I would like to add it.

Cheers
