### ISSUE TITLE
Override Recipient(s) via Twig

### ISSUE THREAD

**Issue by jstnthms** [jadwigo/SimpleForms#46]
I didn't immediately see a way to override recipients via Twig using your extension, and ended up writing my own so I could do this:

```
{{ myform(form_name, to) }}
```

I needed to do it this way because I wanted the recipient email address to be configurable through a value in the CMS/database, and not config files.

So, is there a way to override the recipients of emails through the Twig function? If not, could something like this be easily added?

**Comment by jadwigo** [comment]
It is not really designed as such but you might be able to use a combination of the variables override https://github.com/jadwigo/SimpleForms#overriding-values and the `use_as` parameter on a hidden field:  https://github.com/jadwigo/SimpleForms#email-input-with-extra-recipient.

Your field may be configured as such:

``` yml
recipient:
  type: hidden
  use_as: to_email
  value: example@example.com # for a fallback default value that is needed
```

And calling the form from the template (with an email address in a loaded record as record.to_email_example_value)

``` twig
{{ simpleform('formname', { 'recipient' : record.to_email_example_value } ) }}
```
